const date =new Date()
const year = date.getFullYear();
const month = date.getMonth();
const day = date.getDate();
const hour = date.getHours();
const minutes = date.getMinutes();
const displayDate = day+'/'+(month+1)+'/'+year+'-'+hour+':'
+minutes;
const Footer = () => {
  return (
    <div className="flex justify-between">
        <p>TechMasters - <span>{displayDate}</span></p>
         <div className="flex gap-4">
         <a className="footer-a" href="https://www.flaticon.com/free-icons/user" title="user icons">
        User icons created by Freepik - Flaticon
      </a>
      <p>/</p>
      <a className="footer-a" href="https://www.canva.com/ai-image-generator/" title="images">Images generated by Canva AI Free Image Generator</a>
    </div>

    </div>
   
  )
}

export default Footer